export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'

export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST'
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS'
export const SEND_OTP_FAILED = 'SEND_OTP_FAILED'

export const VERYFY_OTP_REQUEST = 'VERYFY_OTP_REQUEST'
export const VERYFY_OTP_SUCCESS = 'VERYFY_OTP_SUCCESS'
export const VERYFY_OTP_FAILED = 'VERYFY_OTP_FAILED'

export const PASSWORD_UPDATE_REQUEST = 'PASSWORD_UPDATE_REQUEST'
export const PASSWORD_UPDATE_SUCCESS = 'PASSWORD_UPDATE_SUCCESS'
export const PASSWORD_UPDATE_FAILED = 'PASSWORD_UPDATE_FAILED'